Repository PurposeDevelopment/bnb-frontend, pull requests merged in 2020-02, with the labels that each got.

#25 Feature/bnb select
  src/components/bnb-bullet-list/styles.scss
  src/components/bnb-bullet-list/template.ts
  src/components/bnb-error-message/bnb-error-message.ts
  src/components/bnb-error-message/defines.ts
  src/components/bnb-error-message/index.ts
  src/components/bnb-error-message/scaffolding/bnb-error-message.hbs
  src/components/bnb-error-message/styles.scss
  src/components/bnb-error-message/template.ts
  src/components/bnb-headline/bnb-headline.ts
  src/components/bnb-paragraph/scaffolding/bnb-paragraph.hbs
  src/components/bnb-paragraph/styles.scss
  src/components/bnb-select/bnb-select.ts
  src/components/bnb-select/defines.ts
  src/components/bnb-select/index.ts
  src/components/bnb-select/scaffolding/bnb-select.hbs
  src/components/bnb-select/styles.scss
  src/components/bnb-select/template.ts
  src/pages/10components.bnb-error-message.hbs
  src/pages/10components.bnb-headline.hbs~HEAD
  src/pages/10components.bnb-headline.hbs~develop
  src/pages/10components.bnb-select.hbs
  src/resources/scss/fonts/_fonts.scss
  src/resources/scss/settings/_settings.scss
Labels: enhancement

#26 Freature/bnb input
  .prettierrc.yml
  src/components/bnb-input/bnb-input.ts
  src/components/bnb-input/defines.ts
  src/components/bnb-input/index.ts
  src/components/bnb-input/scaffolding/bnb-input.hbs
  src/components/bnb-input/styles.scss
  src/components/bnb-input/template.ts
  src/pages/10components.bnb-headline.hbs
  src/pages/10components.bnb-input.hbs
  src/resources/scss/layouts/_default.scss
  src/resources/scss/layouts/_grid.scss
  src/resources/scss/layouts/_section.scss
  src/resources/scss/settings/_settings.scss
Labels: enhancement

#17 Feature/bnb button cta
  package.json
  src/components/bnb-button-cta/bnb-button-cta.ts
  src/components/bnb-button-cta/defines.ts
  src/components/bnb-button-cta/index.ts
  src/components/bnb-button-cta/scaffolding/bnb-button-cta.hbs
  src/components/bnb-button-cta/template.ts
  src/pages/10components.bnb-button-cta.hbs
  src/resources/scss/mixins/_addAttributeStyles.scss
Labels: enhancement

#27 Feature/bnb link
  src/components/bnb-button-cta/styles.scss
  src/components/bnb-input/styles.scss
  src/components/bnb-link/bnb-link.ts
  src/components/bnb-link/defines.ts
  src/components/bnb-link/index.ts
  src/components/bnb-link/scaffolding/bnb-link.hbs
  src/components/bnb-link/styles.scss
  src/components/bnb-link/template.ts
  src/components/bnb-select/styles.scss
  src/pages/10components.bnb-link.hbs
  src/resources/scss/_styles.scss
Labels: enhancement

#28 Feature/bnb checkbox
  src/components/bnb-checkbox/bnb-checkbox.ts
  src/components/bnb-checkbox/defines.ts
  src/components/bnb-checkbox/index.ts
  src/components/bnb-checkbox/scaffolding/bnb-checkbox.hbs
  src/components/bnb-checkbox/styles.scss
  src/components/bnb-checkbox/template.ts
  src/pages/10components.bnb-checkbox.hbs
Labels: enhancement

#29 Feature/bnb radio
  src/components/bnb-button-cta/scaffolding/bnb-button-cta 2.hbs
  src/components/bnb-button-cta/styles 2.scss
  src/components/bnb-button-cta/template 2.ts
  src/components/bnb-checkbox/bnb-checkbox 2.ts
  src/components/bnb-checkbox/defines 2.ts
  src/components/bnb-checkbox/index 2.ts
  src/components/bnb-checkbox/template 2.ts
  src/components/bnb-error-message/bnb-error-message 2.ts
  src/components/bnb-error-message/defines 2.ts
  src/components/bnb-error-message/index 2.ts
  src/components/bnb-error-message/scaffolding/bnb-error-message 2.hbs
  src/components/bnb-error-message/styles 2.scss
  src/components/bnb-error-message/template 2.ts
  src/components/bnb-headline/bnb-headline 2.ts
  src/components/bnb-headline/defines 2.ts
  src/components/bnb-headline/h1 2.scss
  src/components/bnb-headline/h2 2.scss
  src/components/bnb-headline/h3 2.scss
  src/components/bnb-headline/h4 2.scss
  src/components/bnb-headline/index 2.ts
  src/components/bnb-headline/scaffolding/bnb-headline 2.hbs
  src/components/bnb-headline/template 2.ts
  src/components/bnb-input/bnb-input 2.ts
  src/components/bnb-input/defines 2.ts
  src/components/bnb-input/index 2.ts
  src/components/bnb-input/scaffolding/bnb-input 2.hbs
  src/components/bnb-input/styles 2.scss
  src/components/bnb-input/template 2.ts
  src/components/bnb-link/bnb-link 2.ts
  src/components/bnb-link/defines 2.ts
  src/components/bnb-link/index 2.ts
  src/components/bnb-link/scaffolding/bnb-link 2.hbs
  src/components/bnb-link/styles 2.scss
  src/components/bnb-link/template 2.ts
  src/components/bnb-paragraph/bnb-paragraph 2.ts
  src/components/bnb-paragraph/defines 2.ts
  src/components/bnb-paragraph/index 2.ts
  src/components/bnb-paragraph/scaffolding/bnb-paragraph 2.hbs
  src/components/bnb-paragraph/styles 2.scss
  src/components/bnb-paragraph/template 2.ts
  src/components/bnb-radio/bnb-radio.ts
  src/components/bnb-radio/defines.ts
  src/components/bnb-radio/index.ts
  src/components/bnb-radio/scaffolding/bnb-radio.hbs
  src/components/bnb-radio/styles.scss
  src/components/bnb-radio/template.ts
  src/components/bnb-select/bnb-select 2.ts
  src/components/bnb-select/defines 2.ts
  src/components/bnb-select/index 2.ts
  src/components/bnb-select/scaffolding/bnb-select 2.hbs
  src/components/bnb-select/styles 2.scss
  src/components/bnb-select/template 2.ts
  src/pages/10components.bnb-radio.hbs
  src/resources/scss/mixins/_addAttributeStyles 2.scss
  src/resources/scss/mixins/_breakpoints 2.scss
  src/resources/scss/mixins/_functions 2.scss
  src/resources/scss/mixins/_hoverDevicesOnly 2.scss
  src/resources/scss/mixins/_slotted 2.scss
Labels: enhancement

#32 Feature/bullet list
  src/components/bnb-bullet-item/scaffolding/bnb-bullet-item.hbs
  src/components/bnb-bullet-item/styles.scss
  src/components/bnb-bullet-item/template.ts
  src/components/bnb-bullet-list/scaffolding/bnb-bullet-list.hbs
  src/components/bnb-bullet-list/styles.scss
  src/components/cms/bnb-cms-info-box/bnb-cms-info-box.ts
  src/components/cms/bnb-cms-info-box/scaffolding/bnb-cms-info-box.hbs
  src/components/cms/bnb-cms-info-box/styles.scss
  src/components/cms/bnb-cms-text-icon/bnb-cms-text-icon.ts
  src/components/cms/bnb-cms-text-icon/scaffolding/bnb-cms-text-icon.hbs
  src/components/cms/bnb-cms-text-icon/template.ts
Labels: enhancement

#34 Feature/bnb article info
  src/_assets/img/avatar.png
  src/components/bnb-article-info/bnb-article-info.ts
  src/components/bnb-article-info/defines.ts
  src/components/bnb-article-info/index.ts
  src/components/bnb-article-info/scaffolding/bnb-article-info.hbs
  src/components/bnb-article-info/styles.scss
  src/components/bnb-article-info/template.ts
  src/pages/10components.bnb-article-info.hbs
  src/resources/scss/_styles.scss
Labels: enhancement

#35 Feature/image video youtube components
  src/components/bnb-image/bnb-image.ts
  src/components/bnb-image/defines.ts
  src/components/bnb-image/scaffolding/bnb-image.hbs
  src/components/bnb-image/styles.scss
  src/components/bnb-image/template.ts
  src/components/bnb-video/bnb-video.ts
  src/components/bnb-video/scaffolding/bnb-video.hbs
Labels: enhancement

#37 Feature/adopt new styles
  package.json
  src/components/bnb-bullet-item/styles.scss
  src/components/bnb-bullet-list/bnb-bullet-list.ts
  src/components/bnb-bullet-list/scaffolding/bnb-bullet-list.hbs
  src/components/bnb-bullet-list/styles.scss
  src/components/bnb-button-cta/styles.scss
  src/components/bnb-headline/h1.scss
  src/components/bnb-headline/h2.scss
  src/components/bnb-headline/h3.scss
  src/components/bnb-headline/h4.scss
  src/components/bnb-headline/scaffolding/bnb-headline.hbs
  src/components/bnb-headline/template.ts
  src/components/bnb-icon/Icons/index.ts
  src/components/bnb-icon/Icons/svg/3pax.svg
  src/components/bnb-icon/Icons/svg/bildmarke.svg
  src/components/bnb-icon/Icons/svg/facebook.svg
  src/components/bnb-icon/Icons/svg/facebook_small.svg
  src/components/bnb-icon/Icons/svg/iconset-no-spacing.svg
  src/components/bnb-icon/Icons/svg/iconset-spacing-right.svg
  src/components/bnb-icon/Icons/svg/instagram.svg
  src/components/bnb-icon/Icons/svg/instagram_small.svg
  src/components/bnb-icon/Icons/svg/movie.svg
  src/components/bnb-icon/Icons/svg/play_youtube.svg
  src/components/bnb-icon/Icons/svg/search.svg
  src/components/bnb-icon/Icons/svg/share.svg
  src/components/bnb-icon/Icons/svg/twitter.svg
  src/components/bnb-icon/Icons/svg/twitter_small.svg
  src/components/bnb-icon/scaffolding/bnb-icon.hbs
  src/components/cms/bnb-cms-info-box/bnb-cms-info-box.ts
  src/components/cms/bnb-cms-info-box/defines.ts
  src/components/cms/bnb-cms-info-box/scaffolding/bnb-cms-info-box.hbs
  src/components/cms/bnb-cms-info-box/styles.scss
  src/components/cms/bnb-cms-info-box/template.ts
  src/components/cms/bnb-cms-text-icon/bnb-cms-text-icon.ts
  src/components/cms/bnb-cms-text-icon/defines.ts
  src/components/cms/bnb-cms-text-icon/scaffolding/bnb-cms-text-icon.hbs
  src/components/cms/bnb-cms-text-icon/styles.scss
  src/components/cms/bnb-cms-text-icon/template.ts
  src/components/cms/bnb-cms-text-text/bnb-cms-text-text.ts
  src/components/cms/bnb-cms-text-text/defines.ts
  src/components/cms/bnb-cms-text-text/scaffolding/bnb-cms-text-text.hbs
  src/components/cms/bnb-cms-text-text/styles.scss
  src/components/cms/bnb-cms-text-text/template.ts
  src/resources/scss/_styles.scss
  src/resources/scss/base/_margins.scss
  src/resources/scss/fonts/_fonts.scss
  src/resources/scss/layouts/_grid.scss
  src/resources/scss/layouts/_section.scss
  src/resources/scss/mixins/_cmsCompontents.scss
  src/resources/scss/settings/_settings.scss
Labels: enhancement

#38 Feature/cms text image
  src/_assets/img/testbild.jpg
  src/_assets/img/testbild_1024.jpeg
  src/_assets/img/testbild_1440.jpeg
  src/_assets/img/testbild_1920.jpeg
  src/_assets/img/testbild_300.jpeg
  src/_assets/img/testbild_600.jpeg
  src/_assets/img/testbild_landscape.jpg
  src/_assets/img/testbild_landscape_1024.jpeg
  src/_assets/img/testbild_landscape_1440.jpeg
  src/_assets/img/testbild_landscape_1920.jpeg
  src/_assets/img/testbild_landscape_300.jpeg
  src/_assets/img/testbild_landscape_600.jpeg
  src/components/bnb-image/styles.scss
  src/components/bnb-paragraph/styles.scss
  src/components/cms/bnb-cms-text-image/bnb-cms-text-image.ts
  src/components/cms/bnb-cms-text-image/defines.ts
  src/components/cms/bnb-cms-text-image/index.ts
  src/components/cms/bnb-cms-text-image/scaffolding/bnb-cms-text-image.hbs
  src/components/cms/bnb-cms-text-image/styles.scss
  src/components/cms/bnb-cms-text-image/template.ts
  src/pages/00cms-components.bnb-cms-text-image.hbs
Labels: enhancement

#39 Feature/bnb share
  src/components/bnb-icon/Icons/svg/facebook.svg
  src/components/bnb-icon/Icons/svg/facebook_small.svg
  src/components/bnb-icon/Icons/svg/linkedin.svg
  src/components/bnb-icon/Icons/svg/twitter.svg
  src/components/bnb-icon/Icons/svg/twitter_small.svg
  src/components/bnb-icon/styles.scss
  src/components/bnb-share/bnb-share.ts
  src/components/bnb-share/defines.ts
  src/components/bnb-share/index.ts
  src/components/bnb-share/scaffolding/bnb-share.hbs
  src/components/bnb-share/styles.scss
  src/components/bnb-share/template.ts
  src/pages/10components.bnb-share.hbs
  src/resources/scss/settings/_settings.scss
Labels: enhancement

#40 Feature/bnb follow us
  src/components/bnb-follow/bnb-follow.ts
  src/components/bnb-follow/defines.ts
  src/components/bnb-follow/index.ts
  src/components/bnb-follow/scaffolding/bnb-follow.hbs
  src/components/bnb-follow/styles.scss
  src/components/bnb-follow/template.ts
  src/components/bnb-icon/Icons/svg/facebook_small.svg
  src/components/bnb-icon/Icons/svg/instagram_small.svg
  src/components/bnb-icon/Icons/svg/twitter_small.svg
  src/pages/10components.bnb-follow.hbs
  src/resources/scss/settings/_settings.scss
Labels: enhancement

#41 Feature/bnb footer
  src/components/bnb-button-cta/scaffolding/bnb-button-cta.hbs
  src/components/bnb-button-cta/styles.scss
  src/components/bnb-link/styles.scss
  src/components/cms/bnb-cms-footer/bnb-cms-footer.ts
  src/components/cms/bnb-cms-footer/defines.ts
  src/components/cms/bnb-cms-footer/index.ts
  src/components/cms/bnb-cms-footer/scaffolding/bnb-cms-footer.hbs
  src/components/cms/bnb-cms-footer/styles.scss
  src/components/cms/bnb-cms-footer/template.ts
  src/pages/00cms-components.bnb-cms-footer.hbs
Labels: enhancement

#42 Feature/bnb navigation
  src/components/bnb-button-cta/styles.scss
  src/components/bnb-follow/styles.scss
  src/components/bnb-icon/Icons/index.ts
  src/components/bnb-icon/Icons/svg/schriftzug.svg
  src/components/bnb-icon/scaffolding/bnb-icon.hbs
  src/components/cms/bnb-cms-footer/template.ts
  src/components/cms/bnb-cms-navigation/bnb-cms-navigation.ts
  src/components/cms/bnb-cms-navigation/defines.ts
  src/components/cms/bnb-cms-navigation/index.ts
  src/components/cms/bnb-cms-navigation/scaffolding/bnb-cms-navigation.hbs
  src/components/cms/bnb-cms-navigation/styles.scss
  src/components/cms/bnb-cms-navigation/template.ts
  src/pages/00cms-components.bnb-cms-navigation.hbs
  src/resources/scss/settings/_settings.scss
Labels: enhancement

#44 Feature/bnb stage
  page-data/assets/img/avatar.png
  page-data/assets/img/stage.jpg
  page-data/assets/img/stage_1024.jpeg
  page-data/assets/img/stage_1440.jpeg
  page-data/assets/img/stage_1920.jpeg
  page-data/assets/img/stage_300.jpeg
  page-data/assets/img/stage_600.jpeg
  page-data/assets/img/testbild.jpg
  page-data/assets/img/testbild_1024.jpeg
  page-data/assets/img/testbild_1440.jpeg
  page-data/assets/img/testbild_1920.jpeg
  page-data/assets/img/testbild_300.jpeg
  page-data/assets/img/testbild_600.jpeg
  page-data/assets/img/testbild_landscape.jpg
  page-data/assets/img/testbild_landscape_1024.jpeg
  page-data/assets/img/testbild_landscape_1440.jpeg
  page-data/assets/img/testbild_landscape_1920.jpeg
  page-data/assets/img/testbild_landscape_300.jpeg
  page-data/assets/img/testbild_landscape_600.jpeg
  page-data/index.html
  src/_assets/img/stage.jpg
  src/_assets/img/stage_1024.jpeg
  src/_assets/img/stage_1440.jpeg
  src/_assets/img/stage_1920.jpeg
  src/_assets/img/stage_300.jpeg
  src/_assets/img/stage_600.jpeg
  src/components/bnb-button-cta/defines.ts
  src/components/bnb-button-cta/styles.scss
  src/components/bnb-follow/styles.scss
  src/components/bnb-headline/h1.scss
  src/components/bnb-link/styles.scss
  src/components/cms/bnb-cms-footer/scaffolding/bnb-cms-footer.hbs
  src/components/cms/bnb-cms-footer/styles.scss
  src/components/cms/bnb-cms-footer/template.ts
  src/components/cms/bnb-cms-navigation/template.ts
  src/components/cms/bnb-cms-stage/bnb-cms-stage.ts
  src/components/cms/bnb-cms-stage/defines.ts
  src/components/cms/bnb-cms-stage/index.ts
  src/components/cms/bnb-cms-stage/scaffolding/bnb-cms-stage.hbs
  src/components/cms/bnb-cms-stage/styles.scss
  src/components/cms/bnb-cms-stage/template.ts
  src/components/cms/bnb-cms-text-icon/styles.scss
  src/pages/00cms-components.bnb-cms-stage.hbs
  src/resources/scss/mixins/_cmsCompontents.scss
Labels: enhancement

#45 Feature/add website pages hbs files
  src/components/cms/bnb-cms-footer/styles.scss
  src/components/cms/bnb-cms-info-box/styles.scss
  src/components/cms/bnb-cms-navigation/styles.scss
  src/components/cms/bnb-cms-text-image/styles.scss
  src/components/cms/bnb-cms-text-image/template.ts
  src/components/cms/bnb-cms-text-text/styles.scss
  src/pages/00pages.home.hbs
  src/pages/01cms-components.bnb-cms-footer.hbs
  src/pages/01cms-components.bnb-cms-info-box.hbs
  src/pages/01cms-components.bnb-cms-navigation.hbs
  src/pages/01cms-components.bnb-cms-stage.hbs
  src/pages/01cms-components.bnb-cms-text-icon.hbs
  src/pages/01cms-components.bnb-cms-text-image.hbs
  src/pages/01cms-components.bnb-cms-text-text.hbs
  src/scaffolding/home.hbs
Labels: enhancement

#58 Feature/bnb cms claim
  page-data/about-us.html
  page-data/contact.html
  page-data/index.html
  src/components/bnb-accordion/bnb-accordion.ts
  src/components/bnb-accordion/defines.ts
  src/components/bnb-accordion/index.ts
  src/components/bnb-accordion/scaffolding/bnb-accordion.hbs
  src/components/bnb-accordion/styles.scss
  src/components/bnb-accordion/template.ts
  src/components/bnb-headline/h1.scss
  src/components/bnb-headline/h2.scss
  src/components/bnb-headline/h3.scss
  src/components/bnb-icon/Icons/index.ts
  src/components/bnb-icon/Icons/svg/cross.svg
  src/components/cms/bnb-cms-claims/bnb-cms-claims.ts
  src/components/cms/bnb-cms-claims/defines.ts
  src/components/cms/bnb-cms-claims/index.ts
  src/components/cms/bnb-cms-claims/scaffolding/bnb-cms-claims.hbs
  src/components/cms/bnb-cms-claims/styles.scss
  src/components/cms/bnb-cms-claims/template.ts
  src/components/cms/bnb-cms-navigation/styles.scss
  src/components/cms/bnb-cms-navigation/template.ts
  src/components/cms/bnb-cms-stage/styles.scss
  src/pages/00pages.about-us.hbs
  src/pages/01cms-components.bnb-cms-claims.hbs
  src/pages/10components.bnb-accordion.hbs
  src/resources/scss/mixins/_cmsCompontents.scss
  src/resources/scss/settings/_settings.scss
  src/scaffolding/about-us.hbs
Labels: enhancement

#60 Fix/summary of bugfixes
  src/components/bnb-button-cta/bnb-button-cta.ts
  src/components/bnb-button-cta/defines.ts
  src/components/bnb-button-cta/template.ts
  src/components/bnb-checkbox/bnb-checkbox.ts
  src/components/bnb-checkbox/defines.ts
  src/components/bnb-checkbox/styles.scss
  src/components/bnb-checkbox/template.ts
  src/components/bnb-textarea/bnb-textarea.ts
  src/components/bnb-textarea/defines.ts
  src/components/bnb-textarea/template.ts
  src/components/cms/bnb-cms-contact/template.ts
  src/components/cms/bnb-cms-navigation/styles.scss
  src/components/cms/bnb-cms-navigation/template.ts
Labels: bug

#62 Feature/bnb cms sub stage
  src/components/cms/bnb-cms-stage/defines.ts
  src/components/cms/bnb-cms-stage/styles.scss
  src/components/cms/bnb-cms-sub-stage/bnb-cms-sub-stage.ts
  src/components/cms/bnb-cms-sub-stage/defines.ts
  src/components/cms/bnb-cms-sub-stage/index.ts
  src/components/cms/bnb-cms-sub-stage/scaffolding/bnb-cms-sub-stage.hbs
  src/components/cms/bnb-cms-sub-stage/styles.scss
  src/components/cms/bnb-cms-sub-stage/template.ts
  src/components/cms/bnb-cms-text-icon/bnb-cms-text-icon.ts
  src/components/cms/bnb-cms-text-icon/defines.ts
  src/components/cms/bnb-cms-text-icon/scaffolding/bnb-cms-text-icon.hbs
  src/components/cms/bnb-cms-text-icon/styles.scss
  src/components/cms/bnb-cms-text-icon/template.ts
  src/pages/00pages.data-protection.hbs
  src/pages/01cms-components.bnb-cms-sub-stage.hbs
  src/scaffolding/data-protection.hbs
Labels: enhancement

#63 Feature/newsletter component
  page-data/about-us.html
  page-data/contact.html
  page-data/index.html
  src/components/bnb-headline/h3.scss
  src/components/bnb-newsletter/bnb-newsletter.ts
  src/components/bnb-newsletter/index.ts
  src/components/bnb-newsletter/scaffolding/bnb-newsletter.hbs
  src/components/bnb-newsletter/styles.scss
  src/components/bnb-newsletter/template.ts
  src/components/cms/bnb-cms-contact/styles.scss
  src/components/cms/bnb-cms-newsletter-form/bnb-cms-newsletter-form.ts
  src/components/cms/bnb-cms-newsletter-form/defines.ts
  src/components/cms/bnb-cms-newsletter-form/index.ts
  src/components/cms/bnb-cms-newsletter-form/scaffolding/bnb-cms-newsletter-form.hbs
  src/components/cms/bnb-cms-newsletter-form/styles.scss
  src/components/cms/bnb-cms-newsletter-form/template.ts
  src/components/cms/bnb-cms-stage/styles.scss
  src/components/cms/bnb-cms-sub-stage/styles.scss
  src/components/cms/bnb-cms-text-icon/styles.scss
  src/components/cms/bnb-cms-text-icon/template.ts
  src/components/cms/bnb-cms-text-image/styles.scss
  src/pages/01cms-components.bnb-cms-newsletter-form.hbs
  src/pages/10components.bnb-newsletter.hbs
  src/resources/scss/_styles.scss
  src/resources/scss/base/_margins.scss
  src/resources/scss/mixins/_breakpoints.scss
  src/resources/scss/mixins/_buttonSizes.scss
  src/resources/scss/mixins/_cmsCompontents.scss
  src/resources/scss/settings/_settings.scss
  src/scaffolding/about-us.hbs
  src/scaffolding/contact.hbs
  src/scaffolding/data-protection.hbs
  src/scaffolding/home.hbs
Labels: feature

#83 Feature/bnb partner component
  package.json
  src/components/bnb-icon/Icons/index.ts
  src/components/bnb-icon/Icons/svg/play.svg
  src/components/bnb-icon/scaffolding/bnb-icon.hbs
  src/components/cms/bnb-cms-partner/bnb-cms-partner.ts
  src/components/cms/bnb-cms-partner/defines.ts
  src/components/cms/bnb-cms-partner/index.ts
  src/components/cms/bnb-cms-partner/scaffolding/bnb-cms-partner.hbs
  src/components/cms/bnb-cms-partner/styles.scss
  src/components/cms/bnb-cms-partner/template.ts
  src/pages/01cms-components.bnb-cms-partner.hbs
Labels: feature

#84 Feature/adopt footer changes
  src/components/bnb-follow/template.ts
  src/components/bnb-link/styles.scss
  src/components/cms/bnb-cms-footer/styles.scss
  src/components/cms/bnb-cms-footer/template.ts
  src/resources/scss/fonts/_fonts.scss
Labels: feature

#85 Feature/set current page in menu
  src/components/cms/bnb-cms-footer/template.ts
  src/components/cms/bnb-cms-navigation/styles.scss
  src/components/cms/bnb-cms-navigation/template.ts
  src/pages/00pages.claims.hbs
  src/pages/00pages.faqs.hbs
  src/pages/00pages.get-started.hbs
  src/scaffolding/about-us.hbs
  src/scaffolding/claims.hbs
  src/scaffolding/faqs.hbs
  src/scaffolding/get-started.hbs
Labels: feature

#86 Feature/new styles on claims
  page-data/index.html
  src/components/bnb-accordion/styles.scss
  src/components/bnb-accordion/template.ts
  src/components/bnb-headline/h1.scss
  src/components/bnb-icon/Icons/index.ts
  src/components/bnb-icon/Icons/svg/arrow.svg
  src/components/bnb-icon/styles.scss
  src/components/cms/bnb-cms-claims/bnb-cms-claims.ts
  src/components/cms/bnb-cms-claims/defines.ts
  src/components/cms/bnb-cms-claims/scaffolding/bnb-cms-claims.hbs
  src/components/cms/bnb-cms-claims/styles.scss
  src/components/cms/bnb-cms-claims/template.ts
  src/components/cms/bnb-cms-navigation/template.ts
  src/components/cms/bnb-cms-stage/bnb-cms-stage.ts
  src/components/cms/bnb-cms-stage/scaffolding/bnb-cms-stage.hbs
  src/components/cms/bnb-cms-stage/styles.scss
  src/components/cms/bnb-cms-stage/template.ts
  src/resources/scss/settings/_settings.scss
  src/scaffolding/claims.hbs
  src/scaffolding/faqs.hbs
  src/scaffolding/get-started.hbs
  src/scaffolding/home.hbs
Labels: feature

#87 fix: 🐛 invert colors on bnb-cms-info-box component
  src/components/bnb-bullet-item/styles.scss
  src/components/cms/bnb-cms-info-box/scaffolding/bnb-cms-info-box.hbs
  src/components/cms/bnb-cms-info-box/styles.scss
  src/components/cms/bnb-cms-info-box/template.ts
Labels: bug

#88 Feature/bnb list component
  src/components/bnb-icon/Icons/svg/bullet.svg
  src/components/bnb-list-item/bnb-list-item.ts
  src/components/bnb-list-item/defines.ts
  src/components/bnb-list-item/index.ts
  src/components/bnb-list-item/styles.scss
  src/components/bnb-list-item/template.ts
  src/components/bnb-list/bnb-list.ts
  src/components/bnb-list/defines.ts
  src/components/bnb-list/index.ts
  src/components/bnb-list/scaffolding/bnb-list.hbs
  src/components/bnb-list/styles.scss
  src/components/bnb-list/template.ts
  src/components/cms/bnb-cms-partner/styles.scss
  src/components/cms/bnb-cms-partner/template.ts
  src/components/cms/bnb-cms-text-icon/bnb-cms-text-icon.ts
  src/components/cms/bnb-cms-text-icon/scaffolding/bnb-cms-text-icon.hbs
  src/components/cms/bnb-cms-text-icon/styles.scss
  src/components/cms/bnb-cms-text-icon/template.ts
  src/pages/10components.bnb-list.hbs
  src/scaffolding/about-us.hbs
Labels: feature

#89 Fix/smaller findings on stage and checkbox
  src/components/bnb-checkbox/styles.scss
  src/components/cms/bnb-cms-stage/styles.scss
  src/components/cms/bnb-cms-sub-stage/bnb-cms-sub-stage.ts
  src/components/cms/bnb-cms-sub-stage/defines.ts
  src/components/cms/bnb-cms-sub-stage/styles.scss
  src/components/cms/bnb-cms-sub-stage/template.ts
  src/components/cms/bnb-cms-text-icon/styles.scss
  src/pages/00pages.imprint.hbs
  src/scaffolding/data-protection.hbs
  src/scaffolding/imprint.hbs
Labels: bug

#91 fix: 🐛 added instagram link for follow component
  src/components/bnb-follow/template.ts
Labels: bug

#92 fix: 🐛 make checkbox clickable
  src/components/bnb-newsletter/template.ts
Labels: bug

#93 fix: 🐛 add tribble icon and adopt sizes
  page-data/index.html
  src/components/bnb-icon/Icons/index.ts
  src/components/bnb-icon/Icons/svg/2er-icon.svg
  src/components/bnb-icon/Icons/svg/3er-icon.svg
  src/components/cms/bnb-cms-stage/scaffolding/bnb-cms-stage.hbs
  src/components/cms/bnb-cms-stage/styles.scss
  src/components/cms/bnb-cms-text-icon/scaffolding/bnb-cms-text-icon.hbs
  src/resources/scss/settings/_settings.scss
  src/scaffolding/about-us.hbs
  src/scaffolding/claims.hbs
  src/scaffolding/data-protection.hbs
  src/scaffolding/faqs.hbs
  src/scaffolding/get-started.hbs
  src/scaffolding/home.hbs
  src/scaffolding/imprint.hbs
Labels: bug

#95 Feature/add favicon
  src/_assets/favicon/android-icon-144x144.png
  src/_assets/favicon/android-icon-192x192.png
  src/_assets/favicon/android-icon-36x36.png
  src/_assets/favicon/android-icon-48x48.png
  src/_assets/favicon/android-icon-72x72.png
  src/_assets/favicon/android-icon-96x96.png
  src/_assets/favicon/apple-icon-114x114.png
  src/_assets/favicon/apple-icon-120x120.png
  src/_assets/favicon/apple-icon-144x144.png
  src/_assets/favicon/apple-icon-152x152.png
  src/_assets/favicon/apple-icon-180x180.png
  src/_assets/favicon/apple-icon-57x57.png
  src/_assets/favicon/apple-icon-60x60.png
  src/_assets/favicon/apple-icon-72x72.png
  src/_assets/favicon/apple-icon-76x76.png
  src/_assets/favicon/apple-icon-precomposed.png
  src/_assets/favicon/apple-icon.png
  src/_assets/favicon/browserconfig.xml
  src/_assets/favicon/favicon-16x16.png
  src/_assets/favicon/favicon-32x32.png
  src/_assets/favicon/favicon-96x96.png
  src/_assets/favicon/favicon.ico
  src/_assets/favicon/manifest.json
  src/_assets/favicon/ms-icon-144x144.png
  src/_assets/favicon/ms-icon-150x150.png
  src/_assets/favicon/ms-icon-310x310.png
  src/_assets/favicon/ms-icon-70x70.png
  src/layouts/includes/htmlhead.favicons.hbs
  src/layouts/includes/htmltag.hbs
  src/layouts/layout.default.hbs
Labels: feature

#104 Bugfix/burger icon
  src/components/bnb-checkbox/styles.scss
  src/components/cms/bnb-cms-navigation/styles.scss
Labels: bug

#107 Fix/white background on cms components
  src/components/cms/bnb-cms-text-icon/styles.scss
  src/scaffolding/home.hbs
Labels: bug

#115 fix: 🐛 remove cookie bot and banner scripts
  src/layouts/includes/htmlhead.scripts.hbs
  src/layouts/includes/scripts.hbs
Labels: bug

#114 Fix/background color and favicon
  src/components/cms/bnb-cms-partner/styles.scss
  src/components/cms/bnb-cms-text-image/styles.scss
  src/resources/favicon.png
Labels: bug

#117 Feature/copyright in image
  src/components/bnb-image/scaffolding/bnb-image.hbs
  src/components/bnb-image/styles.scss
  src/components/bnb-image/template.ts
  src/components/cms/bnb-cms-text-image/bnb-cms-text-image.ts
  src/components/cms/bnb-cms-text-image/defines.ts
  src/components/cms/bnb-cms-text-image/scaffolding/bnb-cms-text-image.hbs
  src/components/cms/bnb-cms-text-image/template.ts
  src/scaffolding/about-us.hbs
Labels: feature

#116 fix: 🐛 refactor sizing on cms-info-box component
  src/components/bnb-bullet-item/styles.scss
  src/components/cms/bnb-cms-partner/styles.scss
  src/components/cms/bnb-cms-partner/template.ts
Labels: bug

#119 Feature/bnb youtube
  src/components/bnb-youtube/bnb-youtube.ts
  src/components/bnb-youtube/defines.ts
  src/components/bnb-youtube/scaffolding/bnb-youtube.hbs
  src/components/bnb-youtube/styles.scss
  src/components/bnb-youtube/template.ts
  src/components/cms/bnb-cms-youtube/bnb-cms-youtube.ts
  src/components/cms/bnb-cms-youtube/defines.ts
  src/components/cms/bnb-cms-youtube/index.ts
  src/components/cms/bnb-cms-youtube/scaffolding/bnb-cms-youtube.hbs
  src/components/cms/bnb-cms-youtube/styles.scss
  src/components/cms/bnb-cms-youtube/template.ts
  src/pages/01cms-components.bnb-cms-youtube.hbs
  src/scaffolding/home.hbs
Labels: feature

#122 Feature/implement new texts
  src/components/bnb-accordion/bnb-accordion.ts
  src/components/bnb-accordion/defines.ts
  src/components/bnb-accordion/scaffolding/bnb-accordion.hbs
  src/components/bnb-accordion/styles.scss
  src/components/bnb-accordion/template.ts
  src/components/bnb-youtube/template.ts
  src/components/cms/bnb-cms-claims/styles.scss
  src/components/cms/bnb-cms-claims/template.ts
  src/components/cms/bnb-cms-stage/styles.scss
  src/scaffolding/data-protection.hbs
  src/scaffolding/faqs.hbs
  src/scaffolding/imprint.hbs
Labels: feature

#139 Fix/text changes
  src/components/bnb-bullet-item/styles.scss
  src/components/bnb-button-cta/bnb-button-cta.ts
  src/components/bnb-button-cta/defines.ts
  src/components/bnb-button-cta/scaffolding/bnb-button-cta.hbs
  src/components/bnb-button-cta/styles.scss
  src/components/bnb-button-cta/template.ts
  src/components/bnb-loading-spinner/template.ts
  src/components/bnb-newsletter/styles.scss
  src/components/bnb-newsletter/template.ts
  src/components/cms/bnb-cms-contact/template.ts
  src/components/cms/bnb-cms-footer/template.ts
  src/components/cms/bnb-cms-stage/defines.ts
  src/components/cms/bnb-cms-sub-stage/scaffolding/bnb-cms-sub-stage.hbs
  src/components/cms/bnb-cms-text-icon/defines.ts
  src/components/cms/bnb-cms-text-icon/scaffolding/bnb-cms-text-icon.hbs
  src/components/cms/bnb-cms-text-icon/template.ts
  src/scaffolding/about-us.hbs
  src/scaffolding/claims.hbs
  src/scaffolding/faqs.hbs
  src/scaffolding/get-started.hbs
  src/scaffolding/home.hbs
  src/scaffolding/imprint.hbs
Labels: text-change

#141 Fix/testing issues
  src/components/bnb-button-cta/styles.scss
  src/components/bnb-image/styles.scss
  src/components/bnb-input/bnb-input.ts
  src/components/cms/bnb-cms-navigation/styles.scss
Labels: bug

#142 fix: 🐛 add open first accordion function to accordion component
  src/components/bnb-accordion/bnb-accordion.ts
Labels: bug
